### ISSUE TITLE
Reply URL

### ISSUE THREAD

**Issue by readyxrm** [bguidinger/Xrm.ReportRenderer#1]
This solution is awesome.  Great work!

Just a FYI for the Canadian Data Centers I needed to use "https://canada-001.consent.azure-apim.net/redirect" as the reply URL to work correctly.  This might affect other geos as well.  Thought I would mention it.

My only complaint is that I would have liked to have this solution 6 months earlier... :)

Cheers
Nick

**Comment by bguidinger** [comment]
Good catch on that!  Microsoft doesn't have a published list of the reply URL's (that I can find), but I think I cracked their complex naming convention.  I've updated the documentation accordingly.
