### ISSUE TITLE
Action 'Render Report' failed

### ISSUE THREAD

**Issue by JuliaStreatfield** [bguidinger/Xrm.ReportRenderer#10]
Hi
I've seen this has already been logged but just wanted to add my two pennorth.
I have a custom report that has no parameters.  I've done a simple flow that has a trigger and then Render Report, with report name, output to PDF, and invoiceid.  
Running the Flow returns BadRequest; Status code 400; Headers below
Cache-Control
	no-cache
Set-Cookie	
	ReqClientId=573b446b-8379-4424-a44f-f609973a763a; expires=Thu, 17-Jan-2069 14:18:01 GMT; path=/; secure; HttpOnly,orgId=77331774-6be2-4486-87c3-2b51aa13a864; expires=Thu, 17-Jan-2069 14:18:01 GMT; path=/; secure; HttpOnly,ApplicationGatewayAffinity=37f8ee44e952a9cb07f16ab89cb87ac47a89fc732e9fa81a69e9a1dc94ea43c1;Path=/;Domain=cbidev.crm4.dynamics.com

x-ms-service-request-id	
	24517817-d4ce-4bf5-8c77-85f7278832c5
REQ_ID	
	24517817-d4ce-4bf5-8c77-85f7278832c5,24517817-d4ce-4bf5-8c77-85f7278832c5
x-ms-ratelimit-burst-remaining-xrm-requests
	59986
x-ms-ratelimit-time-remaining-xrm-requests
	11,992.25
OData-Version
	4.0
Date
	Thu, 17 Jan 2019 14:18:04 GMT
Content-Length
	3058
Content-Type
	application/json; odata.metadata=minimal
Expires
	-1

Error message "something went wrong" (can send whole content if required).

I've checked the registration in crm with plugin registration tool and it's all fine.

Please help!  If I can get the report to render I then have to attach it to an email to send but that's another story...

Many thanks
Jules

**Comment by JuliaStreatfield** [comment]
@bguidinger hi can you help please?  Seems there are a few of us with the same issue? Many thanks Jules

**Comment by bguidinger** [comment]
@JuliaStreatfield can you provide some more details about the report and how you are calling RenderReport from Flow?  You mention invoiceid...is that a parameter for the report?

**Comment by JuliaStreatfield** [comment]
Hi Bob

I only have two fields on the report to make it simple for testing – name and invoiceid.  No parameters.

Here is the layout of my Flow (or one of them anyway, I tried many different ways):
[cid:image002.jpg@01D4DF31.8EA81A40]

Made up of:
[cid:image010.jpg@01D4DF31.8EA81A40]

[cid:image011.jpg@01D4DF31.8EA81A40]

Condition is a Boolean field on the invoice entity used for the trigger.

[cid:image012.jpg@01D4DF31.8EA81A40]

The report is loaded into CRM.

Of course it may be that I just haven’t set it up correctly.  I did find some of the instructions on GitHub a bit difficult to follow!

Does that give you enough to go on?

Kind regards
Julia

Julia Streatfield
D: +44 (0)20 7395 8214 | M: +44 (0)7837 263 082

**Comment by bguidinger** [comment]
Looks like the images didn't come through.  Can you comment directly on GitHub and attach the images?

**Comment by JuliaStreatfield** [comment]
I hope this document upload works, let me know if not.
Many thanks

[Settings for ReportRenderer Flow.docx](https://github.com/bguidinger/Xrm.ReportScheduler/files/2992426/Settings.for.ReportRenderer.Flow.docx)

**Comment by bguidinger** [comment]
Excellent, the attachment came through, and I think I see what the issue is.

When creating the Parameter variable, you need to specify the Type as "Object", and pass in a JSON object.  For example:

```
{  
  'Invoice': 'value'
}
```

Of course, replace 'value' with the Invoice object by using dynamic content.  You may need to parse the ID out of the Invoice object first, but I'm not 100% sure on that.

**Comment by JuliaStreatfield** [comment]
I know nothing about json so I’ve tried this – on Initialize Variable:
            Name    Invoice
            Type     Object
            Value    json(triggerBody()?[‘invoiceid’]) – using Expression/conversion functions/json(value) where I replace ‘value’ with invoiceid using dynamic content

When I test that, the Condition fails : ActionConditionFailed. The execution of template action ‘Condition’ is skipped: the ‘runAfter’ condition for action ‘Initialize_variable’ is not satisfied. Expected status values ‘Succeeded’ and actual value ‘Failed’.

Initialize variable failure: InvalidTemplate. Unable to process template language expressions in action 'Initialize_variable' inputs at line '1' and column '2581': 'The template language function 'json' parameter is not valid. The provided value 'adeb1243-c8b9-4053-8803-0cc325abec30' cannot be parsed: 'Unexpected character encountered while parsing value: a. Path '', line 0, position 0.'. Please see https://aka.ms/logicexpressions#json for usage details.'.

So I’m not even getting as far as testing the condition, which I did before, when if ‘no’ then email2 is sent (if ‘yes’ then email1 is sent).

I think I’m going to have to give up on this unless there’s anything else you can suggest.  I wasn’t sure what you meant by ‘you may need to parse the ID out of the Invoice object first).

Cheers
Jules

Julia Streatfield
D: +44 (0)20 7395 8214 | M: +44 (0)7837 263 082

**Comment by bguidinger** [comment]
Here is an example flow which renders the Account Summary report (which uses a parameter).  Note: you will have to replace the GUID of the Account in the FetchXML with a valid ID.

Hopefully this helps.

[ReportRenderer-Example_20190505141720.zip](https://github.com/bguidinger/Xrm.ReportScheduler/files/3145627/ReportRenderer-Example_20190505141720.zip)

**Comment by pjmcewan** [comment]
I have the same issue, and I tried the sample after changing the report id and account id but still get the 400 -- something went wrong -- error

Is there any way to debug through this somehow?

I tried using Postman and can get the report list, but can't render a report

{
    "error": {
        "code": "0x80040265",
        "message": "Something went wrong.",
        "innererror": {
            "message": "Something went wrong.",
            "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]",
            "stacktrace": "   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext, Dictionary`2 optionalParameters)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Execute(OrganizationRequest request, ExecutionContext executionContext)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.ExecuteOperation(CrmODataExecutionContext context, EdmOperation edmOperation, Dictionary`2 parameters, Dictionary`2 boundParameters)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.ProcessOperationRequest(String operationName, Dictionary`2 operationParameters, EntityReference entityReference, String boundEntityName, String boundEntityType)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.<>c__DisplayClass11_0.<PostBoundAction>b__0()\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
        }
    }
}

**Comment by bguidinger** [comment]
@pjmcewan There currently isn't great logging in the plugin which does the report rendering (where the "Something went wrong" message is coming from).  I'll try to add some in the next couple of weeks.

**Comment by bguidinger** [comment]
@pjmcewan I have added additional logging to the plugin.  Please try the latest version (1.5), and open up a new issue if you are still experiencing issues.
