### ISSUE TITLE
Passing Parameters for certain condition types

### ISSUE THREAD

**Issue by cupacheeno** [bguidinger/Xrm.ReportRenderer#11]
Is it possible to pass parameters for the following type of fields?

- Look Ups (Do we pass the Guid?)
- Date Fields, specifically for operators like Last X Years?

If you could please clarify how to pass these parameters it would be incredibly helpful.

Thanks

**Comment by vkesanam** [comment]
Hi 
For me its not working for Text fields. Can you please help me how i need to pass parameters.

**Comment by JuliaStreatfield** [comment]
Hi
I never got it to work.  But staying on the thread as it would be most useful if someone else does!
Cheers
Jules

Julia Streatfield
D: +44 (0)20 7395 8214 | M: +44 (0)7837 263 082

**Comment by bguidinger** [comment]
Are you guys passing the parameters as a _JSON string_ as described in the [Usage](https://github.com/bguidinger/Xrm.ReportScheduler/blob/master/docs/USAGE.md) guide (specifically steps 3 and 4)?  If your flow doesn't look like the screenshots in that guide, it won't work.  Also, there are differences between custom SSRS reports, and reports created using the Report Wizard.

If you can share more details about the type of reports you're running, and how the parameters are configured, that would be helpful.

**Comment by bguidinger** [comment]
@cupacheeno Are you referring to passing parameters for a "Report Builder" report where you define the query to be used before the report renders?  If so, those parameters are passed as a FetchXML query.  The name of the parameter (i.e. CRM_FilteredAccount) has to be exactly what CRM is expected.  It generally follow the format of CRM_Filtered{EntityName}.

For example:
![image](https://user-images.githubusercontent.com/653364/57195104-51910b80-6f14-11e9-8cf4-c3cb54c54b08.png)

This should resolve your issue.  If not, open this issue back up.  Thanks!
