### ISSUE TITLE
Fail to register custom connector on Flow

### ISSUE THREAD

**Issue by ehandani** [bguidinger/Xrm.ReportRenderer#12]
Hi, I'm stuck at registering my custom connector. I always receive "The reply url specified in the request does not match the reply urls configured for the application". I am sure I have put the correct reply url as indicated in step 6 Azure AD in INSTALL.md. Any idea why?

**Comment by crexin** [comment]
Hi Ehandani,

I was running into this problem as well and found that I had to use the Redirect URL that is on the Security tab of the custom Microsoft Flow Connector (https://global.consent.azure-apim.net/redirect) and copy that and to add it as a Web Redirect URI in the Report Renderer App registration.  After doing this, I was able to test and register the custom connector in Microsoft Flow without an issue.  

Chad Rexin

**Comment by ehandani** [comment]
Thanks Chad!

Strange, I had tried this at first and it didn't work but now it works like a charm! 

Erry Handani
