### ISSUE TITLE
Cannot Render Report, Template or Template Excel using Connector

### ISSUE THREAD

**Issue by ChrisThompNz** [bguidinger/Xrm.ReportRenderer#13]
I’ve created a custom connector for Report Rendering in a trial instance, following the steps provided by you.
Please find below the test results for the APIs used in the Rendering Report Connector.

![pic1](https://user-images.githubusercontent.com/49889939/56548420-27fee880-65d4-11e9-880c-e888f15f9968.jpg)
![pic2](https://user-images.githubusercontent.com/49889939/56548421-27fee880-65d4-11e9-9991-bdb5d9aaeff9.jpg)
![pic3](https://user-images.githubusercontent.com/49889939/56548423-27fee880-65d4-11e9-95d7-76c0b6d71da7.jpg)

The test successfully retrieved report list and query (view in crm) list.
I found the test failed to retrieve document template list.
Test for (/POST/RenderReport (test 4),  /POST/RenderTemplate_Word (test 5) , /POST/RenderTemplate_Excel  (test 6) also returned schema validation issue.

In Dynamics 365 forum, there are a number of people reporting issue getting this Report Rendering connector to work. Unfortunately, no solution mentioned to solve the issue.
There might be an issue with the swagger file potentially?

Do you have any fix to this issue that would be appreciated.

**Comment by bguidinger** [comment]
It can't validate the schema when no data is returned.  This is just a warning that you can ignore.

**Comment by bguidinger** [comment]
@ChrisThompNz can you try this again?  I just tried in a test org that has no document templates.  I received the same response you did, but received a "Validation succeeded" message.  Perhaps the flow team updated their parsing logic.  If you still get the validation error, can you paste the message?  I can't read it in the screenshot.

**Comment by ChrisThompNz** [comment]
Hi there. Thank you for this the validation message is now present. I am how ever now experiencing a generic "Something went wrong" response error when testing the _POST_RenderReport. You are correct the other two I should not expect replies from as there are no templates. I have attached a photo of the test of the connector, first the response and then the request. When I pass in a full object in a flow also with the same parameters it does not work either with the same error. Are you able to advise further? 

Cheers,

![image](https://user-images.githubusercontent.com/49889939/57989476-336c0380-7aef-11e9-8cee-88ed778760a3.png)

![image](https://user-images.githubusercontent.com/49889939/57989496-82199d80-7aef-11e9-9c47-f76b7c381fd4.png)

**Comment by bguidinger** [comment]
@ChrisThompNz does your report have a parameter named Color?  If not, you should remove that from the parameters -- that was just a parameter I was using in my test report.

**Comment by ChrisThompNz** [comment]
Thank you Bob, I should have assumed this. Apologies this implementation had come from me second hand. Cheers for all your assistance. This scheduler will be helping us tremendously. Thank you.
