### ISSUE TITLE
Related to #11 - Parameter passing

### ISSUE THREAD

**Issue by cupacheeno** [bguidinger/Xrm.ReportRenderer#14]
Thanks for the info regarding passing an actual FetchXML query to the report however my query was something much simpler.

For example if the report required me to pass the "Owner" for a required report how would I do so?
I've tried passing the Guid of the User however I end up getting errors with bad requests.

Thanks

**Comment by bguidinger** [comment]
What kind of report is it (out-of-the-box report, Report Builder, custom report created through Visual Studio)?  How is the report parameter set up?  Can you provide a screenshot of what the report looks like when you try to run it?

**Comment by bguidinger** [comment]
Closed due to lack of response.  Feel free to open this back up if you are still experiencing this issue.
