### ISSUE TITLE
GetReportSession failing

### ISSUE THREAD

**Issue by doodlleus** [bguidinger/Xrm.ReportRenderer#15]
Hi There, I have downloaded the source and tried running this as a plugin and direct from code but it all seems to come unstuck at the GetReportSession method.

Regardless of report, the reponse is always the same:

`<!DOCTYPE html><html><head><script type='text/javascript'>window.location.href = '/_common/error/errorhandler.aspx?BackUri=&ErrorCode=0x8004832C&inline=1&Parm0=%0d%0a%0d%0a&Parm1=%28rsItemNotFound%29&RequestUri=%2fCRMReports%2fRSViewer%2fReportViewer.aspx&user_lcid=1033';</script></head><body></body></html>`

Any help would be greatly appreciated

**Comment by bguidinger** [comment]
@doodlleus what is the URL and parameters it's using when getting the session?  I haven't seen this particular error message before...it looks like the SSRS server is saying it can't find the report (rsItemNotFound).

**Comment by bguidinger** [comment]
Also, what region is your CRM environment in?  Which version are you on?  If you try to run the same report from the web interface and capture the network traffic, what URL does CRM use when trying to get the session?

**Comment by bguidinger** [comment]
Closed due to lack of response.  Feel free to open this back up if you are still experiencing this issue.
