### ISSUE TITLE
Operation /GET/Reports was not found in swagger

### ISSUE THREAD

**Issue by Epicity** [bguidinger/Xrm.ReportRenderer#16]
I get this error when choosing the "Render Report" option in Flow selecting the custom connector. The testing actually works inside the custom connection but when I make the flow i get this error.

**Comment by bguidinger** [comment]
Are you using the latest Swagger definition file (from v1.5)?  I did notice when I exported it that the forward-slashes in the operations names were replaced with underscores.  I wonder if something changed in Flow.

**Comment by jyin09** [comment]
I got the same error. 

This (v1.4) is working great on 3 environments that I have. Today when I tried to migrate it to another instances, The same message showed up. And yes, the / was replaced by underscore. it looks like no special characters are allowed in the Operation name.

@bguidinger  are you suggesting V1.5 will address this? when I used V1.5, it started to complain about the reply url too long when I tried to make a connection to it. Is there an updated version of the installation guide for 1.5? Thanks

**Comment by bguidinger** [comment]
It seems that something has definitely changed in Flow.  I'm still investigating this.

@jyin09 can you open up a new issue for the reply URL?  Please include a screenshot if you can.

**Comment by bguidinger** [comment]
I've fixed the "Operation /GET/Reports was not found" issue.  Please use the updated OpenAPI (Swagger) definition on the v1.5 release.

The issue was that the operations that have dynamic values (i.e. Render Report where it pulls in the list of reports) needed to have the `operationId` updated to use underscores.
