### ISSUE TITLE
Cannot install solution

### ISSUE THREAD

**Issue by onyebuchiboss** [bguidinger/Xrm.ReportRenderer#18]
Hi, I am getting errors when importing the solution. saying invalid solution because the 3 XML file expected inside the solution is missing. And if I want to use just the plugin, which of the pipeline stages should i register the plugin against ??

**Comment by bguidinger** [comment]
Can you provide some more details?  Which solution (version) are you trying to import?  What version of Dynamics are you on?  Online/on-prem?  Can you provide the actual error message or a screenshot?

**Comment by onyebuchiboss** [comment]
Thanks for responding swiftly. This is the error - "When attempting to import a solution in Dynamics 365, you encounter the following error:

"The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

Error code 80048060.""
. And its an online instance, version 9.0. Checking the cause on microsoft, it showing me this:

**Comment by onyebuchiboss** [comment]
And If you can tell me what stage to register the plugin, that would be helpful, rather than installing the solution.

**Comment by bguidinger** [comment]
@onyebuchiboss Which zip file are you trying to import?  It sounds like you're using the wrong one.  If you open it up, does it contain a solution.xml file?  I think you may have downloaded the source code zip.

How are you planning on registering the plugin step if you can't install the solution?  The plugin needs to be registered against a custom action.  You could create it manually, but it would be much easier to just install the solution.

**Comment by onyebuchiboss** [comment]
@bguidinger i think i have the raw source i got from downloading the ZIP file on here, where do I find the solution?

**Comment by bguidinger** [comment]
On the Code tab in GitHub, click on [Releases](https://github.com/bguidinger/Xrm.ReportScheduler/releases).

**Comment by onyebuchiboss** [comment]
cheers!

**Comment by onyebuchiboss** [comment]
@bguidinger in the installings instruction, in the custom connector, you just said "upload the OpenAPi", is it any OpenApi created by the user or you have  an already created one ?

**Comment by bguidinger** [comment]
You can find the Open API definition in the Release downloads (it's the swagger.json file).
