### ISSUE TITLE
Output of all the report coming out corrupt

### ISSUE THREAD

**Issue by onyebuchiboss** [bguidinger/Xrm.ReportRenderer#19]
Hi Bob,
Nice job you have done with this, I have finally installed the solution and getting it to work, but the returns a corrupt document. I'm I doing anything wrong ?

**Comment by bguidinger** [comment]
It may be how your Flow is configured.  Are you emailing the document, or saving it somewhere?

**Comment by onyebuchiboss** [comment]
@bguidinger emailing it to myself and its the out of the box excel and word docs as well.

**Comment by onyebuchiboss** [comment]
@bguidinger 

![Capture](https://user-images.githubusercontent.com/17562362/60358302-9b0a4e00-99cd-11e9-87fe-54845fc3aaf9.PNG)

Fine the attached pls. Thanks

**Comment by bguidinger** [comment]
Can you try removing one of the "Output" parameters from the "Attachments Content - 1"?  You should only need one.

**Comment by onyebuchiboss** [comment]
@bguidinger i had only one there initially. But after about the 10th trial, it produced a good doc. Thanks again Bob.
