### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CICCIODALEX** [bguidinger/Xrm.ReportRenderer#2]
Hi,
I installed the solution ReportRenderer_1_4_0_0_managed.zip , configured it but I have this exception

	2018-06-25 21:14:21.435 - Starting execution.
	2018-06-25 21:14:25.505 - The remote server returned an error: (400) Bad Request.
	2018-06-25 21:14:25.505 - Stopping execution.
	
Any suggestion?

**Comment by jyin09** [comment]
I had the same issue with 1.3 and 1.4 - when I tried to test the report rendering, it said the same thing "400 Bad Request".

![image](https://user-images.githubusercontent.com/40505983/41877119-ff5e71f8-7884-11e8-8986-45faf2dede7e.png)

**Comment by bguidinger** [comment]
Are these reports out-of-the-box reports, or custom ones?  Do they require any parameters?  Have you entered the credentials on the solution configuration page in CRM?

**Comment by CICCIODALEX** [comment]
Hi, 
here the answers:
 1) The report is a custom report built using Report Wizard
 2) No, the report doesn't require any parameter
 3) I typed system administrator credentials

Let me know if you can help me

**Comment by jyin09** [comment]
I haven't fully tested it, but today the 400 response was gone.

the only thing that I did was re-entering the credential in the solution config, and making sure I received "updated successfully" - I don't think I got this notification in Internet Explorer, but in Edge (haven't tried Chrome)

**Comment by CICCIODALEX** [comment]
@bguidinger please would you help me fixing the issue?

**Comment by bguidinger** [comment]
@CICCIODALEX Can you use the Plugin Registration Tool to confirm that the credentials were saved in the Secure Configuration for the plugin step?

**Comment by CICCIODALEX** [comment]
@bguidinger yes , I have just checked and I can confirm that in the 3 registered steps in the Secure COnfiguration the credentials are saved

**Comment by bguidinger** [comment]
@CICCIODALEX My apologies for not getting back to you before.  Were you able to get this working?  Still having issues?

**Comment by bguidinger** [comment]
Closing issue due to lack of response.
