### ISSUE TITLE
400 Error while executing report from flow.

### ISSUE THREAD

**Issue by sravanjayi** [bguidinger/Xrm.ReportRenderer#20]
While Executing Render report from flow i am getting following exception. This issue is for all reports, which are having no parameters then also getting same issue. I am using oob report.. "User Summery report."
Note: I am using trail CRM.
![Annotation 2019-07-01 123755](https://user-images.githubusercontent.com/52399206/60417033-fff7bb00-9bfc-11e9-9acf-9d77226d685a.png)

**Issue Details:**
Something went wrong: Value cannot be null.
Parameter name: SecureConfig

**Comment by bguidinger** [comment]
Please follow step 4 of the [installation guide](https://github.com/bguidinger/Xrm.ReportScheduler/blob/master/docs/INSTALL.md).

**Comment by sravanjayi** [comment]
Thank you Bob, It worked for me..
