### ISSUE TITLE
Unable to create connection

### ISSUE THREAD

**Issue by jboehnergp** [bguidinger/Xrm.ReportRenderer#22]
We are getting an error when creating the custom connector. The screens in Azure and Flow have changed since this original installation document was created. Can we get any information about how to set up the new informational lines?

**Comment by bguidinger** [comment]
Could you share the details of the error?  That may help me troubleshoot.

**Comment by jboehnergp** [comment]
Yes – when we go to create a new connection we get this error:
[cid:image002.jpg@01D54231.6B54D4D0]

Thanks,
Joe


Joe Boehner
CRM Specialist
Email: jboehner@gpstrategies.com<mailto:jboehner@gpstrategies.com>
Phone (office): (443) 539-8869 ext. 68869
Phone (mobile): (904) 803-6452

**Comment by aindike** [comment]
> We are getting an error when creating the custom connector. The screens in Azure and Flow have changed since this original installation document was created. Can we get any information about how to set up the new informational lines?

I have connected successfully and It is working correctly.

**Comment by aindike** [comment]
Hi Every one,

Here, I have attached a new azure interface connection screenshots.  Please refer that then you guys can be connected successfully. 
[Azure connection.docx](https://github.com/bguidinger/Xrm.ReportScheduler/files/3444477/Azure.connection.docx)

**Comment by richardhardinguk** [comment]
I'm also having problems creating the custom connector in Flow - with the error "The reply url specified in the request does not match the reply urls configured for the application: '<clientid>'."

This is after accepting the permissions. I've also added the url https://login.microsoftonline.com to the Reply (now Request) URLs in Azure, as that appeared to be the URL the login was coming from instead of https://login.windows.net, but it still didn't help.

**Comment by richardhardinguk** [comment]
> I'm also having problems creating the custom connector in Flow - with the error "The reply url specified in the request does not match the reply urls configured for the application: ''."
> 
> This is after accepting the permissions. I've also added the url https://login.microsoftonline.com to the Reply (now Request) URLs in Azure, as that appeared to be the URL the login was coming from instead of https://login.windows.net, but it still didn't help.

Found my answer in issue #12. Different URL required.

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
