### ISSUE TITLE
Run Template as different user

### ISSUE THREAD

**Issue by andreaPorini** [bguidinger/Xrm.ReportRenderer#23]
Hi @bguidinger ,

thank you for this connector, it's very useful.

I have a enhanchment to propose, I'd like to run my Excel Template as a different user, this way I can use the same view (filtered by "Owned by current user") but having a different context of data for each user that i extract from a List Record action.

Is this possibile?

Best regards,
Andrea

**Comment by bguidinger** [comment]
I don't think this is possible the way you're looking to use it.  The only way it could work like that -- and this would required a code change first -- is if each user configured their own Flow with their own connection (and hence the Flow would run as their user when connected to CRM to run the report).

**Comment by andreaPorini** [comment]
Hi @bguidinger,

I took your code and made a few changes in the plugin "Render" to get it done, in particular:

- in the switch of OnExecute

              case "documenttemplate":
                    var templateColumns = new ColumnSet("documenttype", "associatedentitytypecode");
                    var template = service.Retrieve(target.LogicalName, target.Id, templateColumns);
                    switch (template.GetAttributeValue<OptionSetValue>("documenttype")?.Value)
                    {
                        case 1:
                            var savedView = Guid.Parse(context.InputParameterOrDefault<string>("ViewId"));
                            var callerId = context.InputParameterOrDefault<string>("CallerId");
                            output = renderer.RenderExcelTemplate(template.Id, savedView, callerId);
                            break;
                        case 2:
                            var typeCode = template.GetAttributeValue<string>("associatedentitytypecode");
                            var metadata = service.GetEntityMetadata(typeCode);
                            var recordId = Guid.Parse(context.InputParameterOrDefault<string>("RecordId"));
                            output = renderer.RenderWordTemplate(template.Id, recordId, metadata.ObjectTypeCode ?? 0);
                            break;
                        default:
                            throw new Exception("Invalid document template type.");
                    }
                    break;
I've added a parameter and modified the JSON to support it:
> var callerId = context.InputParameterOrDefault<string>("CallerId");

- Then edited the function **RenderExcelTemplate** as follows:
```
public string RenderExcelTemplate(Guid templateId, Guid viewId, string callerId)
        {
            var url = "/api/data/v9.0/RenderTemplateFromView";
            var data = "{ \"Template\": { \"@odata.type\": \"Microsoft.Dynamics.CRM.documenttemplate\", \"documenttemplateid\": \"" + templateId.ToString("D") + "\"  }, \"View\": { \"@odata.type\": \"Microsoft.Dynamics.CRM.savedquery\", \"savedqueryid\": \"" + viewId.ToString("D") + "\"  } }";

            var request = GetRequest("POST", url, data, true, callerId);
            try
            {
                using (var response = request.GetResponse())
                using (var stream = response.GetResponseStream())
                using (var reader = new StreamReader(stream))
                {
                    var body = reader.ReadToEnd().Parse();
                    return body["ExcelFile"];
                }
            }
            catch (WebException ex)
            {
                using (var stream = ex.Response.GetResponseStream())
                using (var reader = new StreamReader(stream))
                {
                    _logger.Write(reader.ReadToEnd());
                    throw;
                }
            }
        }
```

- Finally, the **GetRequest** this way:

```
private HttpWebRequest GetRequest(string method, string url, string data = null, bool isJson = false, string callerId = null)
        {
            var request = WebRequest.CreateHttp($"{_token.Resource}{url}");
            request.Method = method;
            request.CookieContainer = _cookies;
            if (_token != null)
            {
                request.Headers.Add("Authorization", $"Bearer {_token.AccessToken}");
            }
            if (callerId != null)
            {
                request.Headers.Add("MSCRMCallerID", $"{callerId}");
            }
            request.AutomaticDecompression = DecompressionMethods.GZip;

            _logger.Write($"{request.Method} {request.RequestUri.ToString()}");
            if (string.IsNullOrEmpty(data) == false)
            {
                if (isJson)
                {
                    var body = Encoding.ASCII.GetBytes(data);

                    request.ContentType = "application/json";
                    request.ContentLength = body.Length;

                    using (var stream = request.GetRequestStream())
                    {
                        stream.Write(body, 0, body.Length);
                    }
                }
                else
                {
                    var body = Encoding.ASCII.GetBytes(data);

                    request.ContentType = "application/x-www-form-urlencoded";
                    request.ContentLength = body.Length;

                    using (var stream = request.GetRequestStream())
                    {
                        stream.Write(body, 0, body.Length);
                    }
                }

                //_logger.Write(data);
            }

            return request;
        }
```

With those changes I'm able to impersonate a CRM User by his GUID in Flow or in CRM, setting the Flow to run as ADMIN.

Hope it helps, best regards,
Andrea

**Comment by bguidinger** [comment]
Ah...yes, this would work for Excel and Word templates.  Good catch!  However, if I remember right, I tried this with the SSRS reports, but that service does not respect the MSCRMCallerID header.

Would you mind submitting a PR for this?

**Comment by andreaPorini** [comment]
Done, I've done 3 PR because I'm not so good with GitHub but I've included all the changes I've made!

Andrea

**Comment by onyebuchiboss** [comment]
@andreaPorini pls can you tell me the steps on how you installed in dynamics without installing the solution as a whole, i want to debug the code but needs these steps first.

Thanks.

**Comment by andreaPorini** [comment]
Hi @onyebuchiboss, 

to debug the code you're not obliged to install the solution, if you download the code from GitHub you can use the Console Application that @bguidinger has made for us :)

All the logic is in the plugins so the CA is all you need!

Andrea

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
