### ISSUE TITLE
Update the Setup documents

### ISSUE THREAD

**Issue by Buzzard1970** [bguidinger/Xrm.ReportRenderer#26]
Could you update the Azure set up in the documents I'm new to this but every thing seams to have changed since you made the setup instructions in azure portal. sorry to be a pain

**Comment by bguidinger** [comment]
I'll add this to my to-do list.  Probably won't get to it for a while though.

**Comment by Buzzard1970** [comment]
That’s ok thanks for the reply I do appreciate it


Russell Dodd
 [IQM Group-02sm]
Dynamics CRM Architect
CRM / Resco Mobile Developer
IQM GROUP AUSTRALIA
Mooloolaba QLD AU 4775
IQM GROUP L.L.C Delaware USA 19958<x-apple-data-detectors://68/0>
M: 0408 404 432<tel:0408%20404%20432>
E : rd@iqmgroup.com<mailto:rd@iqmgroup.com>

On 20 Aug 2019, at 11:06 pm, Bob Guidinger <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll add this to my to-do list. Probably won't get to it for a while though.

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
