### ISSUE TITLE
I am getting the same error while calling the RenderReport in Microsoft Flow. However it is retrieving all the reports in the system while testing the custom connector's "_GET_Reports" function.

### ISSUE THREAD

**Issue by olusparks** [bguidinger/Xrm.ReportRenderer#27]
This is exactly what I experience now. I am getting the same error while calling the RenderReport in Microsoft Flow. However it is retrieving all the reports in the system while testing the custom connector's "_GET_Reports" function.

_Originally posted by @jogendarb in https://github.com/bguidinger/Xrm.ReportScheduler/issues/21#issuecomment-518778413_

**Comment by glisp42** [comment]
Just a heads up for anyone else who's having this issue.  I was having the same thing and it turned out to be multifactor authentication being enabled.  Make sure the user (ideally a service account) is a Global Admin and has multifactor authentication disabled.

**Comment by bguidinger** [comment]
@glisp42 you are correct that MFA has to be disabled for the service account.  However, the user does not need to be a Global Administrator.

**Comment by dribblej** [comment]
@bguidinger Thank you for this solution. I am wondering where you are supposed to tweak the MFA for the account. Is this in Azure? Thank you for your time.

**Comment by theapemother** [comment]
@bguidinger @glisp42 By service account do you mean one that is set up from azure to make the custom connector? Is it possible to create a separate account that doesn't have global admin and disabled MFA to assign to this plugin so that the flow runs as wanted?
