### ISSUE TITLE
Not working if Multi Factor Authentication (MFA) is enabled

### ISSUE THREAD

**Issue by nancyahernandez** [bguidinger/Xrm.ReportRenderer#28]
In my case Multi Factor Authentication (MFA) is enabled, and unable to bypass that. Please suggest a way to achieve this.

Below is the error that I get.
{"error":"invalid_grant","error_description":"AADSTS50126: Invalid username or password.\r\nTrace ID: c10c7df5-a926-4e9a-bece-4d6306c2df00\r\nCorrelation ID: aefd02de-612d-4139-8012-719674e19392\r\nTimestamp: 2019-08-20 11:35:04Z","error_codes":[50126],"timestamp":"2019-08-20 11:35:04Z","trace_id":"c10c7df5-a926-4e9a-bece-4d6306c2df00","correlation_id":"aefd02de-612d-4139-8012-719674e19392","error_uri":"https://login.microsoftonline.com/error?code=50126"}

**Comment by bguidinger** [comment]
There is no way to bypass this.  In order for the call to SSRS to succeed, it needs to run as a named user account.  There is no way to handle MFA in a plugin since it's running "headless".

**Comment by nancyahernandez** [comment]
Hi @bguidinger 

Thanks for your reply.

Any workarounds? Even if it means going outside plugin is fine.

**Comment by bguidinger** [comment]
The only workaround would be to disable MFA (which I wouldn't recommend, especially for users that have elevated permissions in CRM).

**Comment by nancyahernandez** [comment]
> The only workaround would be to disable MFA (which I wouldn't recommend, especially for users that have elevated permissions in CRM).

Thanks for your support.
