### ISSUE TITLE
Unable to pass multiple parameters to the report

### ISSUE THREAD

**Issue by sureshkumarsatti** [bguidinger/Xrm.ReportRenderer#32]
Hello Bob, First of all thanks for building this solution. Its very handy to use.

I am trying to schedule a report that expects multiple integer parameters. I have tried passing it by initializing a variable of type object and passing the values as an array as shown below.

{
  "ReportParameter1": [
    "960940000",
    "960940000"
  ]
}

When i run the flow i get this error "Something went wrong: The best overloaded method match for 'System.Net.WebUtility.UrlEncode(string)' has some invalid arguments"

Is there anything obvious that i am missing here?

![flow](https://user-images.githubusercontent.com/37064456/63765498-c387c900-c8e6-11e9-9a30-773bb0360e57.png)

**Comment by bguidinger** [comment]
I'm not 100% sure, but you may have to encode the ReportParameter1 value.
So your initialize variable step would look something like this:

{
  "ReportParameter1": "[\"1234\", \"1234\"]"
}

**Comment by bguidinger** [comment]
@sureshkumarsatti were you able to get this working?

**Comment by jakefarrell** [comment]
is it possible to generate a report with multiple parameters.  e.g. i have a report with Parameter 1 and Parameter 2 both needing different GUIDs passed....

**Comment by bguidinger** [comment]
@jakefarrell yes, it's possible.  Just create the JSON parameter with two properties in it.

```
{
  "Parameter1": "00000000-0000-0000-0000-000000000000",
  "Parameter2": "00000000-0000-0000-0000-000000000000",
}
```

**Comment by jakefarrell** [comment]
that is what i thought i gathered form the documentation, but wanted to ask for sure before going this route.  thank you for the quick response...

**Comment by osantonicola-aia** [comment]
Hi @bguidinger,

i am trying to pass a parameter with multiple values, following the suggestion of your previous post, but i get error.

_{
  "ReportParameter1": "[\\\"1234\", \\"1234\\\"]"
}_

Is this the right way to pass multiple input values for the same parameter?

Thanks in advance for your support.

Roland

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
