### ISSUE TITLE
Can't directly edit components within a managed solution ...

### ISSUE THREAD

**Issue by johnmurray01** [bguidinger/Xrm.ReportRenderer#33]
Message in Dynamics/Power Apps says:
You cannot directly edit the components within a managed solution. If the managed properties for solution components are set to allow customization, you can edit them from another unmanaged solution.

Due to this, I don't seem to be able to set the Username/Password in the Configuration area - after I click submit, nothing happens so I don't know if it has saved or not.

Should I be using the 'Unmanaged' zip file instead? (i.e. ReportRenderer_1_5_0_0.zip instead of ReportRenderer_1_5_0_0_managed.zip)

**Comment by johnmurray01** [comment]
tried loading the 'Unmanaged' file but that gives a warning about not being able to uninstall the components once it's installed (which is not the case for the 'Managed' solution). So I've not loaded the Unmanaged file yet for that reason. I guess this is a standard warning for all unmanaged solutions but would still like your guidance on whether I should stick with Managed if there's a way to bypass the Managed issue from the first post? Or should I go Unmanaged?

Message:
"Changes applied by importing an unmanaged solution cannot be uninstalled. Do not install an unmanaged solution if you want to roll back the changes."

**Comment by johnmurray01** [comment]
Hi @bguidinger - any guidance on the above?

**Comment by bguidinger** [comment]
Use managed. The username and password will disappear after you click submit.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by johnmurray01** [comment]
hi @bguidinger - getting an issue right at the end of installation. when you add a new connection in flow it opens a popup where you try to login, but I get an error saying it can't log me in and then underneath it says "AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application".

Also not sure if I've got the correct Dynamics 365 permission setup - there's a number of options and also some other options greyed out that are not accessible. The options I see are the following but none of them seem to work (although the above issue may not be caused by this?):

- Microsoft Dynamics 365 Apps Integration (Text: Access Dynamics 365 Apps Integration as organization user)
- Data Export Service for Microsoft Dynamics 365 (Text: Have access to Data Export Service for Microsoft Dynamics 365 API)
- Dynamics 365 Business Central (https://dynamics.microsoft.com/business-central/overview/) (Text: Access API as the signed-in user)
- Dynamics CRM (https://admin.services.crm.dynamics.com/) (Text: Access Common Data Service as organization users)
- Dynamics Data Integration (https://IntegratorApp.com) (Text: Access Dynamics Data Integration)

**Comment by bguidinger** [comment]
Look at the first screen when you set up the connection in Flow. That will show you the redirect URI you need to use in your Azure AD app registration. I need to update the documentation as the redirects changed.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by johnmurray01** [comment]
what I see in the browser bar in Flow is https://unitedkingdom.flow.microsoft.com/ ? This still gives me the same error.

**Comment by bguidinger** [comment]
When you set up the connection in Flow, there should be a field in the page that has the redirect URI. Not the address bar.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bguidinger** [comment]
@johnmurray01 were you able to get this working?

**Comment by johnmurray01** [comment]
Hi @bguidinger Having an issue with Connector Status - says "This connection is not authenticated - Update password" - but when i click update password and then click fix connection, it tries to log me in (even though I'm already logged in) to fix it, but it doesn't work - any ideas on what password they're referring to here? My CRM login or my Report Renderer pw? I dont think I can change the Report Renderer pw, can I?

**Comment by johnmurray01** [comment]
ok, i've just uninstalled and reinstalled - that seems to have got rid of the authentication issue.

**Comment by johnmurray01** [comment]
Hi @bguidinger 

Got this error:
Failed with error: 'AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 787e2xxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx(Report Renderer). Resource value from request: xxxuat.crm11.dynamics.com. Resource app ID: 00000007-0000-0000-c000-000000000000. List of valid resources from app registration: 00000003-0000-0000-c000-000000000000. '. Please sign in again.

not sure what i've done wrong here?

**Comment by johnmurray01** [comment]
ok, fixed the permissions issue above - but now when I try to setup the Flow, I'm only seeing a list of 'System Views' in the 'Render Template - Excel' dropdown. I want to be able to run Views (Advanced Finds) I created myself in the 'My Views' section of Dynamics 365. Any ideas how to bring these up?

**Comment by johnmurray01** [comment]
Even when i try to run a System View i get the following error:

OUTPUTS:
Status Code: 400

{
  "error": {
    "code": "0x80040265",
    "message": "Something went wrong: The remote server returned an error: (400) Bad Request.",
    "innererror": {
      "message": "Something went wrong: The remote server returned an error: (400) Bad Request.",
      "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bfxxxxxxxxxxxxxx]]",
      "stacktrace": "   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext, Dictionary`2 optionalParameters)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Execute(OrganizationRequest request, ExecutionContext executionContext)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.ExecuteOperation(CrmODataExecutionContext context, EdmOperation edmOperation, Dictionary`2 parameters, Dictionary`2 boundParameters)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.ProcessOperationRequest(String operationName, Dictionary`2 operationParameters, EntityReference entityReference, String boundEntityName, String boundEntityType)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.<>c__DisplayClass11_0.<PostBoundAction>b__0()\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    }
  }
}

**Comment by johnmurray01** [comment]
Hi @bguidinger - 
2 Issues:
1. Getting error above when running a System View
2. Cant run or even see Views (Advanced Finds) I created myself in the 'My Views' section of Dynamics 365.

**Comment by johnmurray01** [comment]
@bguidinger  bob, anybody there?

**Comment by bguidinger** [comment]
Hi John - I have a little one at home now, and my priorities have shifted.
I do not have much time to dedicate to this project at this time.

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
