### ISSUE TITLE
Unable to import into Dynamics 365

### ISSUE THREAD

**Issue by syaney** [bguidinger/Xrm.ReportRenderer#34]
When attempting to import the ReportRenderer_1_5_0_0_managed.zip file into Dynamics it gives the following error.  File Isn't Valid "The compressed (.zip) file couldn't be uploaded because it's corrupted or doesn't contain valid importable files. I have tried redownloading the zip file but it yields the same error message. I am using Dynamics 365 online Version 1710 (9.1.0.8428)

**Comment by bguidinger** [comment]
Just to confirm, you are downloading the zip file from the [Releases](https://github.com/bguidinger/Xrm.ReportScheduler/releases) section?  Make sure you right-click on the file after it's downloaded and "Unblock" it (assuming you're using Windows).

I just imported it successfully into an org of the same version.  If you still have trouble importing it, can you let me know which files are included in the zip file?

**Comment by syaney** [comment]
I double checked to make sure that it was unblocked and am still unable to import the zip file. The files within the zip are 

![image](https://user-images.githubusercontent.com/55896062/65988184-60dd9c00-e455-11e9-968e-bc0421303bdf.png)

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
