### ISSUE TITLE
Azure App Registration Changes

### ISSUE THREAD

**Issue by janhla** [bguidinger/Xrm.ReportRenderer#36]
Hello, I tried to set up the solution according to the installation guide, but Azure App Registration is changed completely and Reply URLs and Dynamics CRM API are not available now. So what should be the suggested installation process in Azure now? Thank you.

**Comment by bguidinger** [comment]
This has been on my list for a while now (updating the install docs). I'll try to get updated documentation published by the end of the week.

In the meantime, you can get the reply URL when you create the customer connector in Power Automate (Flow). The API permissions for the AD app registration may show up as either CDS or Dynamics 365 now (don't remember without checking). If you find one that has "user_impersonation" that should be the correct one.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by janhla** [comment]
Nice, it would be really great. Now I'm stuck trying to connect Flow Connector with Azure App.

**Comment by bguidinger** [comment]
I have updated the documentation.
