### ISSUE TITLE
Power Automate Create a custom connector changes

### ISSUE THREAD

**Issue by omartarazonahernandez** [bguidinger/Xrm.ReportRenderer#37]
Hello, I tried to replicate your solution but in Power Automate, I can't find the "Import an OpenAPI from URL" option
![imagen](https://user-images.githubusercontent.com/29880184/70426061-ada3ab80-1a72-11ea-8740-3590d881e4fa.png)
What is the new way to do this?. Thank you

**Comment by bguidinger** [comment]
Looks like you might be using a Preview version of Power Automate (or you're in a region that's received the latest train).  In my test org in NAM, I don't see the same screen you do.

Either way, you can access the Custom Connectors under the "Data" tab on the left.  From there you can import the OpenAPI file.
