### ISSUE TITLE
Error 400 - Something went wrong

### ISSUE THREAD

**Issue by jcuevaiis** [bguidinger/Xrm.ReportRenderer#38]
Getting a similar error than what I see in previous Posts.  However I don't see a solution being listed.  I am running a report that has no Parameters required.  Below is the error that I am getting in the Body of the Output error:

{
  "error": {
    "code": "0x80040265",
    "message": "Something went wrong.",
    "innererror": {
      "message": "Something went wrong.",
      "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]",
      "stacktrace": "   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext, Dictionary`2 optionalParameters)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Execute(OrganizationRequest request, ExecutionContext executionContext)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.ExecuteOperation(CrmODataExecutionContext context, EdmOperation edmOperation, Dictionary`2 parameters, Dictionary`2 boundParameters)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.ProcessOperationRequest(String operationName, Dictionary`2 operationParameters, EntityReference entityReference, String boundEntityName, String boundEntityType)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.<>c__DisplayClass11_0.<PostBoundAction>b__0()\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    }
  }
}

**Comment by bguidinger** [comment]
Can you enable plug-in tracing in CRM and send the details from the plug-in trace log?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jcuevaiis** [comment]
Here are the details from the plug-in trace log:

BGuidinger.Reports.Render
[FormSections_NavigationFlyOut_Button]
Message Name bg_Render undefined
bg_Render
Primary Entity report undefined
report
Operation Type Plug-in undefined
Plug-in

Configuration
General

System Created

Where the event originated. Set to true if it's a system trace; otherwise, false.
System Created Yes System Created-Where the event originated. Set to true if it's a system trace; otherwise, false.
Yes
Type Name
Class name of the plug-in.
Type Name BGuidinger.Reports.Render Type Name-Class name of the plug-in.
BGuidinger.Reports.Render
Message Name
Name of the message that triggered this plug-in.
Message Name bg_Render Message Name-Name of the message that triggered this plug-in.
bg_Render
Primary Entity
Entity, if any, that the plug-in is executed against.
Primary Entity report Primary Entity-Entity, if any, that the plug-in is executed against.
report
Configuration
Unsecured configuration for the plug-in trace log.
Configuration
--
Secure Configuration
Secured configuration for the plug-in trace log.
Secure Configuration
--
Persistence Key
Asynchronous workflow persistence key.
Persistence Key 00000000-0000-0000-0000-000000000000 Persistence Key-Asynchronous workflow persistence key.
00000000-0000-0000-0000-000000000000
Operation Type
Type of custom code.
Operation Type Plug-in Operation Type-Type of custom code.
Plug-in
Plugin Step Id
ID of the plug-in registration step.
Plugin Step Id 4e5d71b3-e86f-e811-a958-000d3a18b4b9 Plugin Step Id-ID of the plug-in registration step.
4e5d71b3-e86f-e811-a958-000d3a18b4b9

Context

Depth
Depth of execution of the plug-in or custom workflow activity.
Depth 1 Depth-Depth of execution of the plug-in or custom workflow activity.
1
Mode
Type of execution.
Mode Synchronous Mode-Type of execution.
Synchronous
Correlation Id
Unique identifier for tracking plug-in or custom workflow activity execution.
Correlation Id 5d83322a-6247-47c4-90c5-8d8872ee2dee Correlation Id-Unique identifier for tracking plug-in or custom workflow activity execution.
5d83322a-6247-47c4-90c5-8d8872ee2dee
Request Id
Unique identifier of the message request.
Request Id 7a2db2ff-069f-4537-8c9c-078f3f21f577 Request Id-Unique identifier of the message request.
7a2db2ff-069f-4537-8c9c-078f3f21f577


Execution
Performance

Execution Start Time
Time, in milliseconds, to execute the request.
Execution Start Time 12/12/2019 10:46 PM Execution Start Time-Time, in milliseconds, to execute the request.
12/12/201910:46 PM
Execution Duration (ms)
Time, in milliseconds, to execute the request.
Execution Duration (ms) 78 Execution Duration (ms)-Time, in milliseconds, to execute the request.
78
Message Block
Trace text from the plug-in.
Message Block 2019-12-13 6:46:32.418 - Starting execution. 2019-12-13 6:46:32.434 - Object reference not set to an instance of an object. 2019-12-13 6:46:32.434 - Stopping execution. Message Block-Trace text from the plug-in.

2019-12-13 6:46:32.418 - Starting execution.
2019-12-13 6:46:32.434 - Object reference not set to an instance of an object.
2019-12-13 6:46:32.434 - Stopping execution.
Exception Details
Details of the exception.
Exception Details Unhandled exception: Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault] Message: Something went wrong.Detail: <OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts"> <ActivityId>c524a7a5-f39c-40b7-a445-70d9348d2c46</ActivityId> <ErrorCode>-2147220891</ErrorCode> <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic"> <KeyValuePairOfstringanyType> <d2p1:key>OperationStatus</d2p1:key> <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">0</d2p1:value> </KeyValuePairOfstringanyType> <KeyValuePairOfstringanyType> <d2p1:key>SubErrorCode</d2p1:key> <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">-2146233088</d2p1:value> </KeyValuePairOfstringanyType> </ErrorDetails> <HelpLink i:nil="true" /> <Message>Something went wrong.</Message> <Timestamp>2019-12-13T06:46:32.4341667Z</Timestamp> <ExceptionRetriable>false</ExceptionRetriable> <ExceptionSource>PluginExecution</ExceptionSource> <InnerFault> <ActivityId>c524a7a5-f39c-40b7-a445-70d9348d2c46</ActivityId> <ErrorCode>-2147220970</ErrorCode> <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" /> <HelpLink i:nil="true" /> <Message>System.NullReferenceException: Object reference not set to an instance of an object. at BGuidinger.Base.Extensions.GetValue[TType](Dictionary`2 config, String key) at BGuidinger.Reports.Render.OnExecute(IPluginProvider provider) at BGuidinger.Base.Plugin.Execute(IServiceProvider serviceProvider): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #B389C663</Message> <Timestamp>2019-12-13T06:46:32.4341667Z</Timestamp> <ExceptionRetriable>false</ExceptionRetriable> <ExceptionSource i:nil="true" /> <InnerFault i:nil="true" /> <OriginalException i:nil="true" /> <TraceText i:nil="true" /> </InnerFault> <OriginalException>Microsoft.Xrm.Sdk.InvalidPluginExecutionException at BGuidinger.Base.Plugin.Execute(IServiceProvider serviceProvider) at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.&lt;&gt;c__DisplayClass15_3.&lt;Execute&gt;b__0() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.Execute(IOrganizationServiceFactory organizationServiceFactory, Dictionary`2 sandboxServices, String pluginTypeName, String pluginConfiguration, String pluginSecureConfig, IPluginExecutionContext requestContext, Boolean enablePluginStackTrace, Boolean chaosFailAppDomain, String crashOnPluginExceptionMessage) at Microsoft.Crm.Sandbox.SandboxWorker.&lt;&gt;c__DisplayClass3_0.&lt;Execute&gt;b__0()</OriginalException> <TraceText> 2019-12-13 6:46:32.418 - Starting execution. 2019-12-13 6:46:32.434 - Object reference not set to an instance of an object. 2019-12-13 6:46:32.434 - Stopping execution. </TraceText> </OrganizationServiceFault> Exception Details-Details of the exception.
Unhandled exception:
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: Something went wrong.Detail:
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
<ActivityId>c524a7a5-f39c-40b7-a445-70d9348d2c46</ActivityId>
<ErrorCode>-2147220891</ErrorCode>
<ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
<KeyValuePairOfstringanyType>
<d2p1:key>OperationStatus</d2p1:key>
<d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">0</d2p1:value>
</KeyValuePairOfstringanyType>
<KeyValuePairOfstringanyType>
<d2p1:key>SubErrorCode</d2p1:key>
<d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">-2146233088</d2p1:value>
</KeyValuePairOfstringanyType>
</ErrorDetails>
<HelpLink i:nil="true" />
<Message>Something went wrong.</Message>
<Timestamp>2019-12-13T06:46:32.4341667Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource>PluginExecution</ExceptionSource>
<InnerFault>
<ActivityId>c524a7a5-f39c-40b7-a445-70d9348d2c46</ActivityId>
<ErrorCode>-2147220970</ErrorCode>
<ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
<HelpLink i:nil="true" />
<Message>System.NullReferenceException: Object reference not set to an instance of an object.
at BGuidinger.Base.Extensions.GetValue[TType](Dictionary`2 config, String key)
at BGuidinger.Reports.Render.OnExecute(IPluginProvider provider)
at BGuidinger.Base.Plugin.Execute(IServiceProvider serviceProvider): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #B389C663</Message>
<Timestamp>2019-12-13T06:46:32.4341667Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource i:nil="true" />
<InnerFault i:nil="true" />
<OriginalException i:nil="true" />
<TraceText i:nil="true" />
</InnerFault>
<OriginalException>Microsoft.Xrm.Sdk.InvalidPluginExecutionException
at BGuidinger.Base.Plugin.Execute(IServiceProvider serviceProvider)
at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.&lt;&gt;c__DisplayClass15_3.&lt;Execute&gt;b__0()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.Execute(IOrganizationServiceFactory organizationServiceFactory, Dictionary`2 sandboxServices, String pluginTypeName, String pluginConfiguration, String pluginSecureConfig, IPluginExecutionContext requestContext, Boolean enablePluginStackTrace, Boolean chaosFailAppDomain, String crashOnPluginExceptionMessage)
at Microsoft.Crm.Sandbox.SandboxWorker.&lt;&gt;c__DisplayClass3_0.&lt;Execute&gt;b__0()</OriginalException>
<TraceText>
2019-12-13 6:46:32.418 - Starting execution.
2019-12-13 6:46:32.434 - Object reference not set to an instance of an object.
2019-12-13 6:46:32.434 - Stopping execution.
</TraceText>
</OrganizationServiceFault>


Juan Cueva
Instant InfoSystems | Information meets expertise.TM
P: 310.750.7204 F: 310.750.7214 E: jcueva@instantinfo.com<mailto:jcueva@instantinfo.com>

**Comment by mikita110891** [comment]
@bguidinger :

i am getting same error.

{
  "error": {
    "code": "0x80040265",
    "message": "Something went wrong: The remote server returned an error: (400) Bad Request.",
    "innererror": {
      "message": "Something went wrong: The remote server returned an error: (400) Bad Request.",
      "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]",
      "stacktrace": "   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext, Dictionary`2 optionalParameters)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Execute(OrganizationRequest request, ExecutionContext executionContext)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.ExecuteOperation(CrmODataExecutionContext context, EdmOperation edmOperation, Dictionary`2 parameters, Dictionary`2 boundParameters)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.ProcessOperationRequest(String operationName, Dictionary`2 operationParameters, EntityReference entityReference, String boundEntityName, String boundEntityType)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.<>c__DisplayClass11_0.<PostBoundAction>b__0()\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    }
  }
}


Could you please look and give me any solution

**Comment by adventureconsultants** [comment]
My error on testing directly after installation is the same as above. The GET requests pass the testing but the POST requests fail.
Is there any update on this? 
It would be great to know if this project still being supported?

**Comment by kmturek** [comment]
Same issue, started when we moved to V9.1 on Dynamics CRM

**Comment by theapemother** [comment]
I have the exact same issue. "Something went wrong: The remote server returned an error: (400) Bad Request." Has anyone found a fix for this?

**Comment by kmturek** [comment]
My issue was my user name and password was incorrect / not matching what the connector had and my account got locked out from too many failed attempts. works fine now

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
