### ISSUE TITLE
Question on Calling ReportScheduler from Web API

### ISSUE THREAD

**Issue by jyin09** [bguidinger/Xrm.ReportRenderer#4]
Hi,

This is more of a silly question than an issue - if I call the action from web api, can I prompt the saving or download of the output?

Thanks,

Jack

Xrm.WebApi.online.execute(request).then(result => {
    var response = JSON.parse(result.responseText);
    var output = response.Output;

    console.log(output); 
}

**Comment by bguidinger** [comment]
@jyin09 I believe you can use the Blob object and the URL.createObjectURL method.  See here: https://developer.mozilla.org/en-US/docs/Web/API/Blob.
