### ISSUE TITLE
Referencing #11 parameters

### ISSUE THREAD

**Issue by kmturek** [bguidinger/Xrm.ReportRenderer#40]
In #11 - You mentioned SSRS reports were different in passing parameters. I am attempting to run a custom SSRS report each month on specified accounts, say fmic_status equals active. How do i run the report on CRM_FilteredAccount on an SSRS report?

**Comment by kmturek** [comment]
figured it out

**Comment by carrollamanda2** [comment]
what was the fix?  i am facing the same issue and cannot figure out how to pass the current record that triggered the flow as the selected record for pre-filtering.

**Comment by kmturek** [comment]
still havent been able to get it to run a a specific account - just runs on all
