### ISSUE TITLE
How to Pass Parameters

### ISSUE THREAD

**Issue by brdmyldz** [bguidinger/Xrm.ReportRenderer#41]
Hi Bob,

Thank you for the awesome work. So I've been using the Report Renderer for a file My boss asked me to make one more automation but I couldn't manage to get it working.

For the previous flows, report renderer easily worked without any parameter passing like you described in the guide. I guess I was lucky because I couldn't figure out where to find the parameters for the specific report.

For this one however, it gives me error code 400 with the message of "Something went wrong: Error while getting report session.  This is most likely an issue with invalid report parameters.". I'm guessing this new flow I'm working on is not working because the data is not coming from the same database compare to others. I believe I should pass the parameters to fix this issue but I'm pretty new to Dynamics 365 environment and I couldn't figure out where to find the parameters for the specific report.

I'm attaching a picture of how the flow error looks like and also pasting the error code below. Error code looks similar to the codes in previous posts but I couldn't figure it out. Maybe if you could help me how to find the JSON body of the parameters that would be great.  I would be super happy if you could take look!

{
  "error": {
    "code": "0x80040265",
    "message": "Something went wrong: Error while getting report session.  This is most likely an issue with invalid report parameters.",
    "innererror": {
      "message": "Something went wrong: Error while getting report session.  This is most likely an issue with invalid report parameters.",
      "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]",
      "stacktrace": "   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext, Dictionary`2 optionalParameters)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Execute(OrganizationRequest request, ExecutionContext executionContext)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.ExecuteOperation(CrmODataExecutionContext context, EdmOperation edmOperation, Dictionary`2 parameters, Dictionary`2 boundParameters)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.ProcessOperationRequest(String operationName, Dictionary`2 operationParameters, EntityReference entityReference, String boundEntityName, String boundEntityType)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.<>c__DisplayClass11_0.<PostBoundAction>b__0()\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    }
  }
}

<img width="514" alt="Screen Shot 2020-02-01 at 4 47 47 PM" src="https://user-images.githubusercontent.com/29903457/73599535-9a610980-4512-11ea-8075-345e179d7089.png">

**Comment by talismanconsulting** [comment]
Your parameters have to be in JSON format and named exactly as they are in the report.  For example:  
Your report parameter is: PositionId

![Snag_1f685466](https://user-images.githubusercontent.com/56944730/77208410-bbcd8300-6ac9-11ea-8c78-cedbbd95b4d1.png)

Then:
![Snag_1f679ee2](https://user-images.githubusercontent.com/56944730/77208358-a22c3b80-6ac9-11ea-8467-3b3010b0b401.png)

**Comment by srinirn** [comment]
Hi, 
I am having the same problem. I am trying with default report "Account Distribution" and trying to pass the parameters for TopAccounts and GroupBy.
Any solution or directions to pass the parameters .

**Comment by adventureconsultants** [comment]
I downloaded the Renderer Report Example zip file linked on https://github.com/bguidinger/Xrm.ReportScheduler/issues/10 and it will allow me to produce a PDF from a system report such as 'Account Summary' but the moment I switch it to a report I have created either using the same "CRM_FilteredAccount" parameter or no parameters required at all I still get "_Something went wrong: Error while getting report session. This is most likely an issue with invalid report parameters_"

I simply don't appear to be able to create a report using the wizard or a custom SSRS report in VS and have it render.

**Comment by shalumalik** [comment]
Hi,
Has anyone resolved this issue? I am also facing the same issue wherein I am providing the exact same values in parameters as used in Report, it's throwing this error.

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
