### ISSUE TITLE
Import Report Renderer Custom renderer does not work 

### ISSUE THREAD

**Issue by michaelurbain** [bguidinger/Xrm.ReportRenderer#42]
Dear,

We are currently integrating the Custom Connector in a solution with a Power Automate Flow.
Then we export the solution from the Dev environnement and try to import it in another Test environnement. The Flow seems completely broken and is not usable and editable any more.

Did you have experienced the same problem  ? Have you any adviced to deploy the Power Automate flow within another environments?  

Any help will be appreciated.

Thanks in advance for your feedback.

Kind Regards,

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
