### ISSUE TITLE
OpenAPI File

### ISSUE THREAD

**Issue by ghost** [bguidinger/Xrm.ReportRenderer#43]
Under the custom connector in Power Automate I name the connection. After that I have the Import an OpenAPI file. Where is this file located?

Did I miss a step with the installation?

Continue is greyed out and when i click on import it wants me to load a json file.

Please advise,

**Comment by bguidinger** [comment]
The OpenAPI file is the "swagger.json" file in the releases.
https://github.com/bguidinger/Xrm.ReportScheduler/releases
