### ISSUE TITLE
PDF Report Not Changing Values

### ISSUE THREAD

**Issue by ghost** [bguidinger/Xrm.ReportRenderer#46]
When I use a custom report and change values such has the last week to the last 15 or 30 or even 60 days and change sorting by a different field. Nothing changes with the PDF from the original run i did but when i run it in Dynamics it shows the proper information.

Any help or ideas would be greatly appreciated,

**Comment by NAngryPole** [comment]
Here is the Parameters i cannot get into FLOW in the variable section;

{
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="true">
  <entity name="report">
    <attribute name="name" />
    <attribute name="reporttypecode" />
    <attribute name="filename" />
    <attribute name="bodyurl" />
    <attribute name="modifiedon" />
    <attribute name="description" />
    <attribute name="reportid" />
    <attribute name="iscustomreport" />
    <order attribute="name" descending="false" />
    <filter type="and">
      <condition attribute="languagecode" operator="eq-userlanguage" />
    </filter>
    <link-entity name="reportvisibility" from="reportid" to="reportid" link-type="inner" alias="ac">
      <filter type="and">
        <condition attribute="visibilitycode" operator="eq" value="1" />
      </filter>
      <link-entity name="report" from="reportid" to="reportid" link-type="inner" alias="ad">
        <filter type="and">
          <condition attribute="name" operator="eq" value="Completed Activities Report" />
        </filter>
      </link-entity>
    </link-entity>
  </entity>
</fetch>
}

**Comment by ghost** [comment]
`{
	"fetch": {
		"entity": {
			"attribute": [
				{
					"_name": "name"
				},
				{
					"_name": "reporttypecode"
				},
				{
					"_name": "filename"
				},
				{
					"_name": "bodyurl"
				},
				{
					"_name": "modifiedon"
				},
				{
					"_name": "description"
				},
				{
					"_name": "reportid"
				},
				{
					"_name": "iscustomreport"
				}
			],
			"order": {
				"_attribute": "name",
				"_descending": "false"
			},
			"filter": {
				"condition": {
					"_attribute": "languagecode",
					"_operator": "eq-userlanguage"
				},
				"_type": "and"
			},
			"link-entity": {
				"filter": {
					"condition": {
						"_attribute": "visibilitycode",
						"_operator": "eq",
						"_value": "1"
					},
					"_type": "and"
				},
				"link-entity": {
					"filter": {
						"condition": {
							"_attribute": "name",
							"_operator": "eq",
							"_value": "Completed Activities Report"
						},
						"_type": "and"
					},
					"_name": "report",
					"_from": "reportid",
					"_to": "reportid",
					"_link-type": "inner",
					"_alias": "ad"
				},
				"_name": "reportvisibility",
				"_from": "reportid",
				"_to": "reportid",
				"_link-type": "inner",
				"_alias": "ac"
			},
			"_name": "report"
		},
		"_version": "1.0",
		"_output-format": "xml-platform",
		"_mapping": "logical",
		"_distinct": "true"
	}`

**Comment by ghost** [comment]
After putting the fetch xml data into the variable I still have no dynamic content available for the Render Report connector in Flow

**Comment by ghost** [comment]
{
  "error": {
    "code": "0x80040265",
    "message": "Something went wrong: Unable to parse report parameters.  Please ensure they are in JSON format.",
    "innererror": {
      "message": "Something went wrong: Unable to parse report parameters.  Please ensure they are in JSON format.",
      "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]",
      "stacktrace": "   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext, Dictionary`2 optionalParameters)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Execute(OrganizationRequest request, ExecutionContext executionContext)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.ExecuteOperation(CrmODataExecutionContext context, EdmOperation edmOperation, Dictionary`2 parameters, Dictionary`2 boundParameters)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.ProcessOperationRequest(String operationName, Dictionary`2 operationParameters, EntityReference entityReference, String boundEntityName, String boundEntityType)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.<>c__DisplayClass11_0.<PostBoundAction>b__0()\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    }
  }
}

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
