### ISSUE TITLE
Using Flow - When Record Selected

### ISSUE THREAD

**Issue by kmturek** [bguidinger/Xrm.ReportRenderer#49]
We are using this application to run a report on selected records and then send to adobe sign for signature. My issue is how to pass the accountid that has been selected into the report for each account selected. Scenario, our user will create a view and run the flow on multiple records. Flow is set up with a when record is selected, then list accounts, what is the correct parameter for the accountid?

Thank you

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
