### ISSUE TITLE
Question - Reg Client Id

### ISSUE THREAD

**Issue by VenkatSappidi** [bguidinger/Xrm.ReportRenderer#5]
How to get  Client Id in the GetToken Method?

I have registered my crm application in Azure AD.  get the application Id , I used that as a Client Id, But I am getting 400 unauthorized error. 

little caveat here that Our Azure AD  will sync local AD,  when I login to CRM it is going to redirect to local adfs site.

   private Token GetToken(string resource, string username, string password)
        {
            var uri = $"https://login.microsoftonline.com/common/oauth2/token";

            var parameters = new Dictionary<string, dynamic>()
            {
                ["grant_type"] = "password",
                **["client_id"] = "2ad88395-b77d-4561-9441-d0e40824f9bc",**

                ["username"] = username,
                ["password"] = password,
                ["resource"] = resource,
            };
      
        }

**Comment by bguidinger** [comment]
Did you give your App Registration permission to CRM Online?

**Comment by wingzeroaa** [comment]
Hi,

I downloaded the test console app, and I have similar error.
My one is (400) bad request.

It is just same place at
using (var response = request.GetResponse())

client_id is the app I registered.
the Required permission has Dynamic CRM Online -> Delegated Permissions -> Access Dynamics 365 as organisation users. 
![image](https://user-images.githubusercontent.com/41313183/47840867-6ecd0c00-de03-11e8-8dfe-e2b079603dce.png)


I even tried with Fiddler
![image](https://user-images.githubusercontent.com/41313183/47840853-64127700-de03-11e8-933a-1454ecc4c082.png)


Regards,
Zhenyu

**Comment by ehandani** [comment]
I'm stuck at registering my custom connector. I always receive "The reply url specified in the request does not match the reply urls configured for the application". I am sure I have put the correct reply url as indicated in step 6 Azure AD in INSTALL.md. Any idea why?

**Comment by bguidinger** [comment]
These questions may be better asked on an Azure AD forum.
