### ISSUE TITLE
Operation failed (400), see response below

### ISSUE THREAD

**Issue by iannicholls** [bguidinger/Xrm.ReportRenderer#54]
I'm struggling to get this to authenticate on the Post renderReport action. he GET messages work ok though. Is there something anyone has found to resolve this? seem to be a common issue.

Header
{
  "allow": "OPTIONS,GET,HEAD,POST",
  "authactivityid": "1cb30778-0b3f-4aba-a80e-8ff2a2552dd9",
  "cache-control": "no-cache",
  "content-length": "121",
  "content-type": "application/json; odata.metadata=minimal",
  "date": "Mon, 23 Nov 2020 19:16:16 GMT",
  "expires": "-1",
  "odata-version": "4.0",
  "public": "OPTIONS,GET,HEAD,POST",
  "req_id": "9a53229f-3072-4e8b-b568-58d1649528c0,9a53229f-3072-4e8b-b568-58d1649528c0",
  "strict-transport-security": "max-age=31536000; includeSubDomains",
  "timing-allow-origin": "*",
  "x-ms-apihub-cached-response": "true",
  "x-ms-ratelimit-burst-remaining-xrm-requests": "5994",
  "x-ms-ratelimit-time-remaining-xrm-requests": "1,190.03",
  "x-ms-service-request-id": "c79386d3-fa38-45f7-bf38-75d348049208,9a53229f-3072-4e8b-b568-58d1649528c0",
  "x-source": "5716920291952617664179253219172142190120103172222910479196172092437220647125516525,177185128133901942250186148824433116227801162272255642135415125305310312874142100"
}

Body
{
  "error": {
    "code": "0x80040265",
    "message": "Something went wrong: The remote server returned an error: (400) Bad Request."
  }
}

**Comment by iannicholls** [comment]
Had some time to dig into this today and it looks like this is the issue. **Access has been blocked by Conditional Access policies.** Will see if I can get the config change to get around it.

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
