### ISSUE TITLE
Usage - how to render Word/Excel from Javascript

### ISSUE THREAD

**Issue by jyin09** [bguidinger/Xrm.ReportRenderer#6]
Hi,

in the usage documentation, I can see the instruction for rendering a report, can this code be used for rendering Word/Excel? or is it possible to do so?

Thanks

Jack

**Comment by jyin09** [comment]
I think I figured it out - when calling Word/Excel template from Javascript, the output remains in original format, is it possible to convert it to PDF? The reason being that, for the javascript call to render a report, I am able to convert the output to PDF, so I am wondering if it's possible for Word/Excel too.

Jack

**Comment by bguidinger** [comment]
You would have to use a third-party library to convert to Word/Excel document to PDF.  The reports are special since they are rendered by SSRS which has native support for exporting as PDF, Word, or Excel.
