### ISSUE TITLE
Something went wrong: The remote server returned an error: (400) Bad Request

### ISSUE THREAD

**Issue by alexy18** [bguidinger/Xrm.ReportRenderer#60]
Hello 

Please help us, we are at a loss, We really need the solution and are unable to implement it in our organization

{
  "error": {
    "code": "0x80040265",
    "message": "Something went wrong: The remote server returned an error: (400) Bad Request."
  }
}

**Comment by alexy18** [comment]
any idea where the problem is ?

![image](https://user-images.githubusercontent.com/78345071/117774377-17b11900-b242-11eb-9e92-987719ee0c3c.png)

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
