### ISSUE TITLE
Wont Import

### ISSUE THREAD

**Issue by Mattw112** [bguidinger/Xrm.ReportRenderer#7]
Getting error "You can only import solutions with a package version of 8.2 or earlier into this organization. Also, you can't import any solutions into this organization that were exported from Microsoft Dynamics 365 2011 or earlier."

I am using the latest release and we are running CRM Online.

Thanks,
Terry

**Comment by ikefy** [comment]
Is ur Dynamics tenant v9.0?

**Comment by Mattw112** [comment]
Version 1612 (8.2.2.2364) (DB 8.2.2.2364) online

How do I get 9?

**Comment by ilnurg77** [comment]
I have same issue in Prod.
Microsoft Dynamics 365
Version 1612 (8.2.2.2364) (DB 8.2.2.2364) online

But it works for my Sandbox with latest version:
Microsoft Dynamics 365
Version 1710 (9.0.2.1470) online

**Comment by bguidinger** [comment]
The solution was exported from a v9.0 environment, and therefore will only import into a v9.0 or higher environment.  Since v8.2 will only be supported online until January 31, 2019, it doesn't make sense to port this solution back to 8.2.
