### ISSUE TITLE
"message": "Bad Request - Error in query syntax.",

### ISSUE THREAD

**Issue by tshortland** [bguidinger/Xrm.ReportRenderer#8]
Hi,

I get the following error when trying to render a report. I've tried an OOB report, a simple, parameter-less SSRS report and get the same response. 

I've checked the secure config in the plugin registration tool as noted in another issue and can see my credentials are saved.

Any ideas greatly appreciated.

Request:
https://europe-001.azure-apim.net/apim/***/reports(SimpleReport)/Microsoft.Dynamics.CRM.bg_Render

Response:
{
  "error": {
    "code": "0x8006088a",
    "message": "Bad Request - Error in query syntax.",
    "innererror": {
      "message": "Bad Request - Error in query syntax.",
      "type": "Microsoft.OData.ODataException",
      "stacktrace": "   at Microsoft.OData.UriParser.SegmentKeyHandler.TryCreateKeySegmentFromParentheses(ODataPathSegment previous, KeySegment previousKeySegment, String parenthesisExpression, ODataUriResolver resolver, ODataPathSegment& keySegment, Boolean enableUriTemplateParsing)\r\n   at Microsoft.OData.UriParser.ODataPathParser.TryBindKeyFromParentheses(String parenthesesSection)\r\n   at Microsoft.OData.UriParser.ODataPathParser.TryCreateSegmentForNavigationSource(String identifier, String parenthesisExpression)\r\n   at Microsoft.OData.UriParser.ODataPathParser.CreateFirstSegment(String segmentText)\r\n   at Microsoft.OData.UriParser.ODataPathParser.ParsePath(ICollection`1 segments)\r\n   at Microsoft.OData.UriParser.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)\r\n   at Microsoft.OData.UriParser.ODataUriParser.Initialize()\r\n   at System.Web.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer, Boolean template)\r\n   at System.Web.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)\r\n   at Microsoft.Crm.Extensibility.ODataV4.Routing.CrmODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)"
    }
  }
}

Thanks,
Tristan

**Comment by bguidinger** [comment]
Does the URL contain "reports(SimpleReport)", or does it have the GUID of the report inside the parentheses?  In order for the Web API call to work, you must use the GUID.

**Comment by tshortland** [comment]
Hi Bob,

Thanks for the reply.

It turns out it wouldn’t work with an account authenticating via AD FS, but using a .onmicroosft.com account worked.

Thanks,


Tristan Shortland
Software Development Director
0345 450 4600
www.infinitygroup.co.uk
Connect with us on LinkedIn, Facebook, Twitter 
GDPR Consultancy: Download our Brochure now.
Infinity Group accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. 
​Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.  [V4323449X]
